name: HCGlowing
version: "${version}"
main: fr.noltox.hcplugins.customplayerglowing.HCGlowing
api-version: "26.3"
description: Sélectionne des profils de glow vanilla rendus par HCPack-CustomAssets.
author: Noltox
website: https://heavencube.fr/
dependencies:
  server:
    HCCore:
      load: BEFORE
      required: true
      join-classpath: true
    HCPlaceholdersExtra:
      load: BEFORE
      required: true
      join-classpath: true
